[package]
build = 'build.rs'
edition = '2021'
name = 'ton_labs_assembler'
version = '1.2.103'

[dependencies]
failure = '0.1'
hex = '0.4'
log = '0.4'
num = '0.4'
num-traits = '0.2'
serde_json = '1.0'
serde = { features = [ 'derive' ], version = '1.0' }
ton_types = { git = 'https://github.com/tonlabs/ever-types.git', tag = '2.0.5' }

[features]
gosh = [  ]
groth = [  ]

