[package]
build = 'build.rs'
edition = '2018'
name = 'ton_labs_assembler'
version = '1.2.61'

[dependencies]
failure = '0.1.7'
hex = '^0.4.0'
log = '0.4.8'
num = '0.4'
num-traits = '0.2'
serde_json = '1.0'
serde = { features = [ 'derive' ], version = '1.0' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.11.8' }

[features]
gosh = [  ]

